export const COUNTRIES = Object.freeze([
    { "bandera": "https://flagcdn.com/ci.svg", "nombre": "Ivory Coast", "nombreES": "Costa de Marfil", "fifa": "CIV" },
    { "bandera": "https://flagcdn.com/it.svg", "nombre": "Italy", "nombreES": "Italia", "fifa": "ITA" },
    { "bandera": "https://flagcdn.com/kg.svg", "nombre": "Kyrgyzstan", "nombreES": "Kirguizistán", "fifa": "KGZ" },
    { "bandera": "https://flagcdn.com/pg.svg", "nombre": "Papua New Guinea", "nombreES": "Papúa Nueva Guinea", "fifa": "PNG" },
    { "bandera": "https://flagcdn.com/fj.svg", "nombre": "Fiji", "nombreES": "Fiyi", "fifa": "FIJ" },
    { "bandera": "https://flagcdn.com/ae.svg", "nombre": "United Arab Emirates", "nombreES": "Emiratos Árabes Unidos", "fifa": "UAE" },
    { "bandera": "https://flagcdn.com/kn.svg", "nombre": "Saint Kitts and Nevis", "nombreES": "San Cristóbal y Nieves", "fifa": "SKN" },
    { "bandera": "https://flagcdn.com/tz.svg", "nombre": "Tanzania", "nombreES": "Tanzania", "fifa": "TAN" },
    { "bandera": "https://flagcdn.com/ao.svg", "nombre": "Angola", "nombreES": "Angola", "fifa": "ANG" },
    { "bandera": "https://flagcdn.com/tg.svg", "nombre": "Togo", "nombreES": "Togo", "fifa": "TOG" },
    { "bandera": "https://flagcdn.com/fi.svg", "nombre": "Finland", "nombreES": "Finlandia", "fifa": "FIN" },
    { "bandera": "https://flagcdn.com/mw.svg", "nombre": "Malawi", "nombreES": "Malawi", "fifa": "MWI" },
    { "bandera": "https://flagcdn.com/ml.svg", "nombre": "Mali", "nombreES": "Mali", "fifa": "MLI" },
    { "bandera": "https://flagcdn.com/uz.svg", "nombre": "Uzbekistan", "nombreES": "Uzbekistán", "fifa": "UZB" },
    { "bandera": "https://flagcdn.com/sn.svg", "nombre": "Senegal", "nombreES": "Senegal", "fifa": "SEN" },
    { "bandera": "https://flagcdn.com/ug.svg", "nombre": "Uganda", "nombreES": "Uganda", "fifa": "UGA" },
    { "bandera": "https://flagcdn.com/dj.svg", "nombre": "Djibouti", "nombreES": "Djibouti", "fifa": "DJI" },
    { "bandera": "https://flagcdn.com/ss.svg", "nombre": "South Sudan", "nombreES": "Sudán del Sur", "fifa": "SSD" },
    { "bandera": "https://flagcdn.com/jp.svg", "nombre": "Japan", "nombreES": "Japón", "fifa": "JPN" },
    { "bandera": "https://flagcdn.com/om.svg", "nombre": "Oman", "nombreES": "Omán", "fifa": "OMA" },
    { "bandera": "https://flagcdn.com/be.svg", "nombre": "Belgium", "nombreES": "Bélgica", "fifa": "BEL" },
    { "bandera": "https://flagcdn.com/fr.svg", "nombre": "France", "nombreES": "Francia", "fifa": "FRA" },
    { "bandera": "https://flagcdn.com/bg.svg", "nombre": "Bulgaria", "nombreES": "Bulgaria", "fifa": "BUL" },
    { "bandera": "https://flagcdn.com/cy.svg", "nombre": "Cyprus", "nombreES": "Chipre", "fifa": "CYP" },
    { "bandera": "https://flagcdn.com/kr.svg", "nombre": "South Korea", "nombreES": "Corea del Sur", "fifa": "KOR" },
    { "bandera": "https://flagcdn.com/mx.svg", "nombre": "Mexico", "nombreES": "México", "fifa": "MEX" },
    { "bandera": "https://flagcdn.com/mk.svg", "nombre": "North Macedonia", "nombreES": "Macedonia del Norte", "fifa": "MKD" },
    { "bandera": "https://flagcdn.com/gy.svg", "nombre": "Guyana", "nombreES": "Guyana", "fifa": "GUY" },
    { "bandera": "https://flagcdn.com/xk.svg", "nombre": "Kosovo", "nombreES": "Kosovo", "fifa": "KVX" },
    { "bandera": "https://flagcdn.com/ma.svg", "nombre": "Morocco", "nombreES": "Marruecos", "fifa": "MAR" },
    { "bandera": "https://flagcdn.com/gi.svg", "nombre": "Gibraltar", "nombreES": "Gibraltar", "fifa": "GIB" },
    { "bandera": "https://flagcdn.com/ad.svg", "nombre": "Andorra", "nombreES": "Andorra", "fifa": "AND" },
    { "bandera": "https://flagcdn.com/gn.svg", "nombre": "Guinea", "nombreES": "Guinea", "fifa": "GUI" },
    { "bandera": "https://flagcdn.com/tc.svg", "nombre": "Turks and Caicos Islands", "nombreES": "Islas Turks y Caicos", "fifa": "TCA" },
    { "bandera": "https://flagcdn.com/sa.svg", "nombre": "Saudi Arabia", "nombreES": "Arabia Saudí", "fifa": "KSA" },
    { "bandera": "https://flagcdn.com/bw.svg", "nombre": "Botswana", "nombreES": "Botswana", "fifa": "BOT" },
    { "bandera": "https://flagcdn.com/km.svg", "nombre": "Comoros", "nombreES": "Comoras", "fifa": "COM" },
    { "bandera": "https://flagcdn.com/bz.svg", "nombre": "Belize", "nombreES": "Belice", "fifa": "BLZ" },
    { "bandera": "https://flagcdn.com/kh.svg", "nombre": "Cambodia", "nombreES": "Camboya", "fifa": "CAM" },
    { "bandera": "https://flagcdn.com/lc.svg", "nombre": "Saint Lucia", "nombreES": "Santa Lucía", "fifa": "LCA" },
    { "bandera": "https://flagcdn.com/mr.svg", "nombre": "Mauritania", "nombreES": "Mauritania", "fifa": "MTN" },
    { "bandera": "https://flagcdn.com/jm.svg", "nombre": "Jamaica", "nombreES": "Jamaica", "fifa": "JAM" },
    { "bandera": "https://flagcdn.com/cv.svg", "nombre": "Cape Verde", "nombreES": "Cabo Verde", "fifa": "CPV" },
    { "bandera": "https://flagcdn.com/na.svg", "nombre": "Namibia", "nombreES": "Namibia", "fifa": "NAM" },
    { "bandera": "https://flagcdn.com/ir.svg", "nombre": "Iran", "nombreES": "Iran", "fifa": "IRN" },
    { "bandera": "https://flagcdn.com/az.svg", "nombre": "Azerbaijan", "nombreES": "Azerbaiyán", "fifa": "AZE" },
    { "bandera": "https://flagcdn.com/ne.svg", "nombre": "Niger", "nombreES": "Níger", "fifa": "NIG" },
    { "bandera": "https://flagcdn.com/la.svg", "nombre": "Laos", "nombreES": "Laos", "fifa": "LAO" },
    { "bandera": "https://flagcdn.com/bf.svg", "nombre": "Burkina Faso", "nombreES": "Burkina Faso", "fifa": "BFA" },
    { "bandera": "https://flagcdn.com/lu.svg", "nombre": "Luxembourg", "nombreES": "Luxemburgo", "fifa": "LUX" },
    { "bandera": "https://flagcdn.com/id.svg", "nombre": "Indonesia", "nombreES": "Indonesia", "fifa": "IDN" },
    { "bandera": "https://flagcdn.com/lb.svg", "nombre": "Lebanon", "nombreES": "Líbano", "fifa": "LBN" },
    { "bandera": "https://flagcdn.com/tr.svg", "nombre": "Turkey", "nombreES": "Turquía", "fifa": "TUR" },
    { "bandera": "https://flagcdn.com/tl.svg", "nombre": "Timor-Leste", "nombreES": "Timor Oriental", "fifa": "TLS" },
    { "bandera": "https://flagcdn.com/zw.svg", "nombre": "Zimbabwe", "nombreES": "Zimbabue", "fifa": "ZIM" },
    { "bandera": "https://flagcdn.com/za.svg", "nombre": "South Africa", "nombreES": "Sudáfrica", "fifa": "RSA" },
    { "bandera": "https://flagcdn.com/am.svg", "nombre": "Armenia", "nombreES": "Armenia", "fifa": "ARM" },
    { "bandera": "https://flagcdn.com/ie.svg", "nombre": "Ireland", "nombreES": "Irlanda", "fifa": "IRL" },
    { "bandera": "https://flagcdn.com/no.svg", "nombre": "Norway", "nombreES": "Noruega", "fifa": "NOR" },
    { "bandera": "https://flagcdn.com/ke.svg", "nombre": "Kenya", "nombreES": "Kenia", "fifa": "KEN" },
    { "bandera": "https://flagcdn.com/kp.svg", "nombre": "North Korea", "nombreES": "Corea del Norte", "fifa": "PRK" },
    { "bandera": "https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_the_Taliban.svg", "nombre": "Afghanistan", "nombreES": "Afganistán", "fifa": "AFG" },
    { "bandera": "https://flagcdn.com/bm.svg", "nombre": "Bermuda", "nombreES": "Bermudas", "fifa": "BER" },
    { "bandera": "https://flagcdn.com/es.svg", "nombre": "Spain", "nombreES": "España", "fifa": "ESP" },
    { "bandera": "https://flagcdn.com/nl.svg", "nombre": "Netherlands", "nombreES": "Países Bajos", "fifa": "NED" },
    { "bandera": "https://flagcdn.com/ni.svg", "nombre": "Nicaragua", "nombreES": "Nicaragua", "fifa": "NCA" },
    { "bandera": "https://flagcdn.com/ls.svg", "nombre": "Lesotho", "nombreES": "Lesotho", "fifa": "LES" },
    { "bandera": "https://flagcdn.com/eg.svg", "nombre": "Egypt", "nombreES": "Egipto", "fifa": "EGY" },
    { "bandera": "https://flagcdn.com/gm.svg", "nombre": "Gambia", "nombreES": "Gambia", "fifa": "GAM" },
    { "bandera": "https://flagcdn.com/br.svg", "nombre": "Brazil", "nombreES": "Brasil", "fifa": "BRA" },
    { "bandera": "https://flagcdn.com/au.svg", "nombre": "Australia", "nombreES": "Australia", "fifa": "AUS" },
    { "bandera": "https://flagcdn.com/bb.svg", "nombre": "Barbados", "nombreES": "Barbados", "fifa": "BRB" },
    { "bandera": "https://flagcdn.com/mg.svg", "nombre": "Madagascar", "nombreES": "Madagascar", "fifa": "MAD" },
    { "bandera": "https://flagcdn.com/pt.svg", "nombre": "Portugal", "nombreES": "Portugal", "fifa": "POR" },
    { "bandera": "https://flagcdn.com/as.svg", "nombre": "American Samoa", "nombreES": "Samoa Americana", "fifa": "ASA" },
    { "bandera": "https://flagcdn.com/tm.svg", "nombre": "Turkmenistan", "nombreES": "Turkmenistán", "fifa": "TKM" },
    { "bandera": "https://flagcdn.com/dm.svg", "nombre": "Dominica", "nombreES": "Dominica", "fifa": "DMA" },
    { "bandera": "https://flagcdn.com/sb.svg", "nombre": "Solomon Islands", "nombreES": "Islas Salomón", "fifa": "SOL" },
    { "bandera": "https://flagcdn.com/rw.svg", "nombre": "Rwanda", "nombreES": "Ruanda", "fifa": "RWA" },
    { "bandera": "https://flagcdn.com/pa.svg", "nombre": "Panama", "nombreES": "Panamá", "fifa": "PAN" },
    { "bandera": "https://flagcdn.com/bs.svg", "nombre": "Bahamas", "nombreES": "Bahamas", "fifa": "BAH" },
    { "bandera": "https://flagcdn.com/me.svg", "nombre": "Montenegro", "nombreES": "Montenegro", "fifa": "MNE" },
    { "bandera": "https://flagcdn.com/ar.svg", "nombre": "Argentina", "nombreES": "Argentina", "fifa": "ARG" },
    { "bandera": "https://flagcdn.com/cu.svg", "nombre": "Cuba", "nombreES": "Cuba", "fifa": "CUB" },
    { "bandera": "https://flagcdn.com/ky.svg", "nombre": "Cayman Islands", "nombreES": "Islas Caimán", "fifa": "CAY" },
    { "bandera": "https://flagcdn.com/kz.svg", "nombre": "Kazakhstan", "nombreES": "Kazajistán", "fifa": "KAZ" },
    { "bandera": "https://flagcdn.com/ru.svg", "nombre": "Russia", "nombreES": "Rusia", "fifa": "RUS" },
    { "bandera": "https://flagcdn.com/in.svg", "nombre": "India", "nombreES": "India", "fifa": "IND" },
    { "bandera": "https://flagcdn.com/vg.svg", "nombre": "British Virgin Islands", "nombreES": "Islas Vírgenes del Reino Unido", "fifa": "VGB" },
    { "bandera": "https://flagcdn.com/gu.svg", "nombre": "Guam", "nombreES": "Guam", "fifa": "GUM" },
    { "bandera": "https://flagcdn.com/mm.svg", "nombre": "Myanmar", "nombreES": "Myanmar", "fifa": "MYA" },
    { "bandera": "https://flagcdn.com/cd.svg", "nombre": "DR Congo", "nombreES": "Congo (Rep. Dem.)", "fifa": "COD" },
    { "bandera": "https://flagcdn.com/mu.svg", "nombre": "Mauritius", "nombreES": "Mauricio", "fifa": "MRI" },
    { "bandera": "https://flagcdn.com/ua.svg", "nombre": "Ukraine", "nombreES": "Ucrania", "fifa": "UKR" },
    { "bandera": "https://flagcdn.com/tj.svg", "nombre": "Tajikistan", "nombreES": "Tayikistán", "fifa": "TJK" },
    { "bandera": "https://flagcdn.com/my.svg", "nombre": "Malaysia", "nombreES": "Malasia", "fifa": "MAS" },
    { "bandera": "https://flagcdn.com/so.svg", "nombre": "Somalia", "nombreES": "Somalia", "fifa": "SOM" },
    { "bandera": "https://flagcdn.com/ag.svg", "nombre": "Antigua and Barbuda", "nombreES": "Antigua y Barbuda", "fifa": "ATG" },
    { "bandera": "https://flagcdn.com/cf.svg", "nombre": "Central African Republic", "nombreES": "República Centroafricana", "fifa": "CTA" },
    { "bandera": "https://flagcdn.com/mo.svg", "nombre": "Macau", "nombreES": "Macao", "fifa": "MAC" },
    { "bandera": "https://flagcdn.com/il.svg", "nombre": "Israel", "nombreES": "Israel", "fifa": "ISR" },
    { "bandera": "https://flagcdn.com/ng.svg", "nombre": "Nigeria", "nombreES": "Nigeria", "fifa": "NGA" },
    { "bandera": "https://flagcdn.com/hn.svg", "nombre": "Honduras", "nombreES": "Honduras", "fifa": "HON" },
    { "bandera": "https://flagcdn.com/sl.svg", "nombre": "Sierra Leone", "nombreES": "Sierra Leone", "fifa": "SLE" },
    { "bandera": "https://flagcdn.com/tn.svg", "nombre": "Tunisia", "nombreES": "Túnez", "fifa": "TUN" },
    { "bandera": "https://flagcdn.com/lt.svg", "nombre": "Lithuania", "nombreES": "Lituania", "fifa": "LTU" },
    { "bandera": "https://flagcdn.com/iq.svg", "nombre": "Iraq", "nombreES": "Irak", "fifa": "IRQ" },
    { "bandera": "https://flagcdn.com/ch.svg", "nombre": "Switzerland", "nombreES": "Suiza", "fifa": "SUI" },
    { "bandera": "https://flagcdn.com/cl.svg", "nombre": "Chile", "nombreES": "Chile", "fifa": "CHI" },
    { "bandera": "https://flagcdn.com/tw.svg", "nombre": "Taiwan", "nombreES": "Taiwán", "fifa": "TPE" },
    { "bandera": "https://flagcdn.com/vn.svg", "nombre": "Vietnam", "nombreES": "Vietnam", "fifa": "VIE" },
    { "bandera": "https://flagcdn.com/bd.svg", "nombre": "Bangladesh", "nombreES": "Bangladesh", "fifa": "BAN" },
    { "bandera": "https://flagcdn.com/vu.svg", "nombre": "Vanuatu", "nombreES": "Vanuatu", "fifa": "VAN" },
    { "bandera": "https://flagcdn.com/pk.svg", "nombre": "Pakistan", "nombreES": "Pakistán", "fifa": "PAK" },
    { "bandera": "https://flagcdn.com/lv.svg", "nombre": "Latvia", "nombreES": "Letonia", "fifa": "LVA" },
    { "bandera": "https://flagcdn.com/mt.svg", "nombre": "Malta", "nombreES": "Malta", "fifa": "MLT" },
    { "bandera": "https://flagcdn.com/sc.svg", "nombre": "Seychelles", "nombreES": "Seychelles", "fifa": "SEY" },
    { "bandera": "https://flagcdn.com/ms.svg", "nombre": "Montserrat", "nombreES": "Montserrat", "fifa": "MSR" },
    { "bandera": "https://flagcdn.com/ai.svg", "nombre": "Anguilla", "nombreES": "Anguilla", "fifa": "AIA" },
    { "bandera": "https://flagcdn.com/gr.svg", "nombre": "Greece", "nombreES": "Grecia", "fifa": "GRE" },
    { "bandera": "https://flagcdn.com/cz.svg", "nombre": "Czechia", "nombreES": "Chequia", "fifa": "CZE" },
    { "bandera": "https://flagcdn.com/zm.svg", "nombre": "Zambia", "nombreES": "Zambia", "fifa": "ZAM" },
    { "bandera": "https://flagcdn.com/hk.svg", "nombre": "Hong Kong", "nombreES": "Hong Kong", "fifa": "HKG" },
    { "bandera": "https://flagcdn.com/us.svg", "nombre": "United States", "nombreES": "Estados Unidos", "fifa": "USA" },
    { "bandera": "https://flagcdn.com/sz.svg", "nombre": "Eswatini", "nombreES": "Suazilandia", "fifa": "SWZ" },
    { "bandera": "https://flagcdn.com/si.svg", "nombre": "Slovenia", "nombreES": "Eslovenia", "fifa": "SVN" },
    { "bandera": "https://flagcdn.com/mv.svg", "nombre": "Maldives", "nombreES": "Maldivas", "fifa": "MDV" },
    { "bandera": "https://flagcdn.com/gh.svg", "nombre": "Ghana", "nombreES": "Ghana", "fifa": "GHA" },
    { "bandera": "https://flagcdn.com/py.svg", "nombre": "Paraguay", "nombreES": "Paraguay", "fifa": "PAR" },
    { "bandera": "https://flagcdn.com/mz.svg", "nombre": "Mozambique", "nombreES": "Mozambique", "fifa": "MOZ" },
    { "bandera": "https://flagcdn.com/ps.svg", "nombre": "Palestine", "nombreES": "Palestina", "fifa": "PLE" },
    { "bandera": "https://flagcdn.com/md.svg", "nombre": "Moldova", "nombreES": "Moldavia", "fifa": "MDA" },
    { "bandera": "https://flagcdn.com/lr.svg", "nombre": "Liberia", "nombreES": "Liberia", "fifa": "LBR" },
    { "bandera": "https://flagcdn.com/li.svg", "nombre": "Liechtenstein", "nombreES": "Liechtenstein", "fifa": "LIE" },
    { "bandera": "https://flagcdn.com/pe.svg", "nombre": "Peru", "nombreES": "Perú", "fifa": "PER" },
    { "bandera": "https://flagcdn.com/qa.svg", "nombre": "Qatar", "nombreES": "Catar", "fifa": "QAT" },
    { "bandera": "https://flagcdn.com/ge.svg", "nombre": "Georgia", "nombreES": "Georgia", "fifa": "GEO" },
    { "bandera": "https://flagcdn.com/ec.svg", "nombre": "Ecuador", "nombreES": "Ecuador", "fifa": "ECU" },
    { "bandera": "https://flagcdn.com/ph.svg", "nombre": "Philippines", "nombreES": "Filipinas", "fifa": "PHI" },
    { "bandera": "https://flagcdn.com/et.svg", "nombre": "Ethiopia", "nombreES": "Etiopía", "fifa": "ETH" },
    { "bandera": "https://flagcdn.com/vi.svg", "nombre": "United States Virgin Islands", "nombreES": "Islas Vírgenes de los Estados Unidos", "fifa": "VIR" },
    { "bandera": "https://flagcdn.com/sy.svg", "nombre": "Syria", "nombreES": "Siria", "fifa": "SYR" },
    { "bandera": "https://flagcdn.com/ro.svg", "nombre": "Romania", "nombreES": "Rumania", "fifa": "ROU" },
    { "bandera": "https://flagcdn.com/gt.svg", "nombre": "Guatemala", "nombreES": "Guatemala", "fifa": "GUA" },
    { "bandera": "https://flagcdn.com/np.svg", "nombre": "Nepal", "nombreES": "Nepal", "fifa": "NEP" },
    { "bandera": "https://flagcdn.com/bj.svg", "nombre": "Benin", "nombreES": "Benín", "fifa": "BEN" },
    { "bandera": "https://flagcdn.com/kw.svg", "nombre": "Kuwait", "nombreES": "Kuwait", "fifa": "KUW" },
    { "bandera": "https://flagcdn.com/sr.svg", "nombre": "Suriname", "nombreES": "Surinam", "fifa": "SUR" },
    { "bandera": "https://flagcdn.com/nc.svg", "nombre": "New Caledonia", "nombreES": "Nueva Caledonia", "fifa": "NCL" },
    { "bandera": "https://flagcdn.com/sd.svg", "nombre": "Sudan", "nombreES": "Sudán", "fifa": "SDN" },
    { "bandera": "https://flagcdn.com/td.svg", "nombre": "Chad", "nombreES": "Chad", "fifa": "CHA" },
    { "bandera": "https://flagcdn.com/uy.svg", "nombre": "Uruguay", "nombreES": "Uruguay", "fifa": "URU" },
    { "bandera": "https://flagcdn.com/ba.svg", "nombre": "Bosnia and Herzegovina", "nombreES": "Bosnia y Herzegovina", "fifa": "BIH" },
    { "bandera": "https://flagcdn.com/tt.svg", "nombre": "Trinidad and Tobago", "nombreES": "Trinidad y Tobago", "fifa": "TRI" },
    { "bandera": "https://flagcdn.com/se.svg", "nombre": "Sweden", "nombreES": "Suecia", "fifa": "SWE" },
    { "bandera": "https://flagcdn.com/is.svg", "nombre": "Iceland", "nombreES": "Islandia", "fifa": "ISL" },
    { "bandera": "https://flagcdn.com/ht.svg", "nombre": "Haiti", "nombreES": "Haití", "fifa": "HAI" },
    { "bandera": "https://flagcdn.com/bn.svg", "nombre": "Brunei", "nombreES": "Brunei", "fifa": "BRU" },
    { "bandera": "https://flagcdn.com/hr.svg", "nombre": "Croatia", "nombreES": "Croacia", "fifa": "CRO" },
    { "bandera": "https://flagcdn.com/mn.svg", "nombre": "Mongolia", "nombreES": "Mongolia", "fifa": "MNG" },
    { "bandera": "https://flagcdn.com/aw.svg", "nombre": "Aruba", "nombreES": "Aruba", "fifa": "ARU" },
    { "bandera": "https://flagcdn.com/cg.svg", "nombre": "Republic of the Congo", "nombreES": "Congo", "fifa": "CGO" },
    { "bandera": "https://flagcdn.com/st.svg", "nombre": "São Tomé and Príncipe", "nombreES": "Santo Tomé y Príncipe", "fifa": "STP" },
    { "bandera": "https://flagcdn.com/ye.svg", "nombre": "Yemen", "nombreES": "Yemen", "fifa": "YEM" },
    { "bandera": "https://flagcdn.com/gq.svg", "nombre": "Equatorial Guinea", "nombreES": "Guinea Ecuatorial", "fifa": "EQG" },
    { "bandera": "https://flagcdn.com/co.svg", "nombre": "Colombia", "nombreES": "Colombia", "fifa": "COL" },
    { "bandera": "https://flagcdn.com/gw.svg", "nombre": "Guinea-Bissau", "nombreES": "Guinea-Bisáu", "fifa": "GNB" },
    { "bandera": "https://flagcdn.com/de.svg", "nombre": "Germany", "nombreES": "Alemania", "fifa": "GER" },
    { "bandera": "https://flagcdn.com/th.svg", "nombre": "Thailand", "nombreES": "Tailandia", "fifa": "THA" },
    { "bandera": "https://flagcdn.com/bt.svg", "nombre": "Bhutan", "nombreES": "Bután", "fifa": "BHU" },
    { "bandera": "https://flagcdn.com/ga.svg", "nombre": "Gabon", "nombreES": "Gabón", "fifa": "GAB" },
    { "bandera": "https://flagcdn.com/lk.svg", "nombre": "Sri Lanka", "nombreES": "Sri Lanka", "fifa": "SRI" },
    { "bandera": "https://flagcdn.com/al.svg", "nombre": "Albania", "nombreES": "Albania", "fifa": "ALB" },
    { "bandera": "https://flagcdn.com/nz.svg", "nombre": "New Zealand", "nombreES": "Nueva Zelanda", "fifa": "NZL" },
    { "bandera": "https://flagcdn.com/dz.svg", "nombre": "Algeria", "nombreES": "Argelia", "fifa": "ALG" },
    { "bandera": "https://flagcdn.com/sm.svg", "nombre": "San Marino", "nombreES": "San Marino", "fifa": "SMR" },
    { "bandera": "https://flagcdn.com/cw.svg", "nombre": "Curaçao", "nombreES": "Curazao", "fifa": "CUW" },
    { "bandera": "https://flagcdn.com/sv.svg", "nombre": "El Salvador", "nombreES": "El Salvador", "fifa": "SLV" },
    { "bandera": "https://flagcdn.com/gd.svg", "nombre": "Grenada", "nombreES": "Grenada", "fifa": "GRN" },
    { "bandera": "https://flagcdn.com/to.svg", "nombre": "Tonga", "nombreES": "Tonga", "fifa": "TGA" },
    { "bandera": "https://flagcdn.com/bi.svg", "nombre": "Burundi", "nombreES": "Burundi", "fifa": "BDI" },
    { "bandera": "https://flagcdn.com/ws.svg", "nombre": "Samoa", "nombreES": "Samoa", "fifa": "SAM" },
    { "bandera": "https://flagcdn.com/dk.svg", "nombre": "Denmark", "nombreES": "Dinamarca", "fifa": "DEN" },
    { "bandera": "https://flagcdn.com/ve.svg", "nombre": "Venezuela", "nombreES": "Venezuela", "fifa": "VEN" },
    { "bandera": "https://flagcdn.com/at.svg", "nombre": "Austria", "nombreES": "Austria", "fifa": "AUT" },
    { "bandera": "https://flagcdn.com/sk.svg", "nombre": "Slovakia", "nombreES": "República Eslovaca", "fifa": "SVK" },
    { "bandera": "https://flagcdn.com/cn.svg", "nombre": "China", "nombreES": "China", "fifa": "CHN" },
    { "bandera": "https://flagcdn.com/bo.svg", "nombre": "Bolivia", "nombreES": "Bolivia", "fifa": "BOL" },
    { "bandera": "https://flagcdn.com/ly.svg", "nombre": "Libya", "nombreES": "Libia", "fifa": "LBY" },
    { "bandera": "https://flagcdn.com/ee.svg", "nombre": "Estonia", "nombreES": "Estonia", "fifa": "EST" },
    { "bandera": "https://flagcdn.com/ck.svg", "nombre": "Cook Islands", "nombreES": "Islas Cook", "fifa": "COK" },
    { "bandera": "https://flagcdn.com/pr.svg", "nombre": "Puerto Rico", "nombreES": "Puerto Rico", "fifa": "PUR" },
    { "bandera": "https://flagcdn.com/by.svg", "nombre": "Belarus", "nombreES": "Bielorrusia", "fifa": "BLR" },
    { "bandera": "https://flagcdn.com/fo.svg", "nombre": "Faroe Islands", "nombreES": "Islas Faroe", "fifa": "FRO" },
    { "bandera": "https://flagcdn.com/vc.svg", "nombre": "Saint Vincent and the Grenadines", "nombreES": "San Vicente y Granadinas", "fifa": "VIN" },
    { "bandera": "https://flagcdn.com/do.svg", "nombre": "Dominican Republic", "nombreES": "República Dominicana", "fifa": "DOM" },
    { "bandera": "https://flagcdn.com/hu.svg", "nombre": "Hungary", "nombreES": "Hungría", "fifa": "HUN" },
    { "bandera": "https://flagcdn.com/bh.svg", "nombre": "Bahrain", "nombreES": "Bahrein", "fifa": "BHR" },
    { "bandera": "https://flagcdn.com/cm.svg", "nombre": "Cameroon", "nombreES": "Camerún", "fifa": "CMR" },
    { "bandera": "https://flagcdn.com/ca.svg", "nombre": "Canada", "nombreES": "Canadá", "fifa": "CAN" },
    { "bandera": "https://flagcdn.com/er.svg", "nombre": "Eritrea", "nombreES": "Eritrea", "fifa": "ERI" },
    { "bandera": "https://flagcdn.com/sg.svg", "nombre": "Singapore", "nombreES": "Singapur", "fifa": "SIN" },
    { "bandera": "https://flagcdn.com/cr.svg", "nombre": "Costa Rica", "nombreES": "Costa Rica", "fifa": "CRC" },
    { "bandera": "https://flagcdn.com/rs.svg", "nombre": "Serbia", "nombreES": "Serbia", "fifa": "SRB" },
    { "bandera": "https://flagcdn.com/pl.svg", "nombre": "Poland", "nombreES": "Polonia", "fifa": "POL" },
    { "bandera": "https://flagcdn.com/jo.svg", "nombre": "Jordan", "nombreES": "Jordania", "fifa": "JOR" },
    { "bandera": "https://flagcdn.com/gb-sct.svg", "nombre": "Scotland", "nombreES": "Escocia", "fifa": "SCT" },
    { "bandera": "https://flagcdn.com/gb-eng.svg", "nombre": "England", "nombreES": "Inglaterra", "fifa": "ENG" },
]);

export const SORTED_COUNTRIES = [...COUNTRIES].sort((a, b) =>
    a.nombreES.localeCompare(b.nombreES, 'es', { sensitivity: 'base' })
);